### ISSUE TITLE
Storage Space Billing Units

### ISSUE THREAD

**Issue by JMuff22** [Lumi-supercomputer/lumi-userguide#40]
In [computing/jobs/billing](https://docs.lumi-supercomputer.eu/computing/jobs/billing/) it states that 

"for storage, your project is allocated GB-hours."
"Storage is billed by volume as well as time. The billing units are GB-hours."

However in [storage#billing](https://docs.lumi-supercomputer.eu/storage/#billing) it states

"The billing units are TB-hours"

Which is correct? There is conflicting information that needs to be resolved.

**Comment by Chroxvi** [comment]
I believe the correct billing unit for storage is "TB-hours" since it is the unit used in Puhuri (the platform used to manage access and resources for all LUMI consortium countries except Finland). The PR in #51 corrects this such that only "TB-hours" is mentioned in the documentation.

The MyCSC platform, used to manage access and resources for Finish LUMI users, uses TiB-hours as the storage billing unit. In the documentation we seem to use GB/GiB, TB/TiB, PB/PiB interchangeably, which seems a bit sketchy. We might be want to strictly use binary prefixes throughout the management platforms and documentation in order to avoid confusion.
